Podfile.lock, README.md, SDK/CalendarStoreSinglePageViewController.swift, SDK/CalendarStoreViewController.swift, SDK/ViewControllers/CalendarItemViewController.swift, SDK/ViewControllers/PageViewController.swift, SDK/ViewControllers/Settings/SettingsDetailViewController.swift, SDK/ViewControllers/Settings/SettingsViewController.swift, SchedJoulesSDK.podspec, iOS-SDK.xcodeproj/project.pbxproj
- The Calendar Store can now be initialized as a single navigation controller, showing only the home page (i.e. no auxiliary pages and settings tab).
- Fixed a bug where the SDK storyboard was not loaded from the resource bundle.
- Removed unnecessary `readSettings()` function.
=> Added `CalendarStoreSinglePageViewController`, fixes #13.

SDK/ViewControllers/Settings/SettingsViewController.swift
Open the settings view, tap on restore purchases, the app won't crash
=> #64 Fix for crash on restore purchases

SDK/Store/StoreManager.swift, SDK/Store/StoreViewController.swift
The apps that use the SDK crash since it can't find image "purchase-intro-1", seems that the problem is that in the SDK the image was assigned using imageLiteral, which apparently casues problems with cocoapods.
This commit also adds a log for the product identifier
=> Fix crash and log product Id

SDK/Store/StoreViewController.swift, SchedJoulesSDK.podspec
This PR fixes the issue about the pod not recognizing an image because the bundle wasn't set.
=> Fix image bundle for store image & podspec update

Podfile, Podfile.lock, iOS-SDK.xcodeproj/project.pbxproj
This version updates cocoa pods to our latest version.
It removes Result from the pod file since it's included in SchedJoulesApiClient and having it here didn't let us update since SchedJoulesApiClient user Result v.4.+
=> SchedJoulesApiclient update to 0.7.3

SDK/CalendarStoreViewController.swift
Based on this comment from a client: "I don't understand what the "Next" tab in the CalendarStore is about? Can you explain what this is?", it was decided to remove the tab from the app. The related elements remain in case we want to add it back in the future.
=> #91 Remove "Next" tab

SDK/Store/StoreViewController.swift
This crash wasn't visible in Xcode 10, but in Xcode 11 GM seeds 1 and 2 you can see it. The crash alert was:
'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
To confirm the fix works, just tap on the red cross of any calendar and wait for the animation of the product to finish.
=> #92 Fix for crash on Xcode 11, when animating the store in a backgorund thread

SDK/Store/StoreManager.swift
One of our clients brought to our attention that restoring purchases was failing for some of his apps, the reason is that we only restore the latest purchase, but some purchases belonged to his products which was causing that our product purchase wasn't restored properly.
=> #96 Filter out the products that don't belong to SchedJoules while restoring purchases

Demo/Info.plist, SDK/ViewControllers/Settings/SettingsViewController.swift
This PR adds a feature available in the old SDK where users had the option to add an email to receive support requests from the public calendars SDK. This feature wasn't scoped but was recently brought up by a client.
To test go to the .plist and look for the key "CalendarStoreFeedbackEmailAddress" after changing it run the app and go to settings, there the new support email will be visible.
=> #93 Add an option in the .plist for users to change the support email for calendars

SDK/Store/StoreViewController.swift
When the error alert in StoreManager was presented, the layout modifications were called from the main thread, in Xcode 11 instead of a warning the app crashes. This PR fixes that bug.
=> #99 Fix for Crash when presenting the error alert of StoreManager

Demo/AppDelegate.swift, Podfile.lock, SDK/CalendarStoreViewController.swift, SDK/Utils/Config.swift, SDK/Utils/Extensions/NotificationName.swift, SDK/ViewControllers/CalendarItemViewController.swift, SDK/ViewControllers/PageViewController.swift, SDK/ViewControllers/WeatherMap/WeatherDetailViewController.swift, iOS-SDK.xcodeproj/project.pbxproj, iOS-SDK.xcodeproj/xcshareddata/xcschemes/iOS-SDK.xcscheme
This Pr includes issues #94 and #95 since their goal is to inform the hosting app about actions in the calendar sdk.
#94 now users can set their launching class to conform to the `CalendarStoreDelegate` and be notified when the CalendarStore is closed.
#95 users can also listen for a notification named `subscribedToCalendar` that will inform them when a user opens a calendar url, informing which the url of the calendar.
=> #94 #95 Inform the hosting app of changes in the calendars

SchedJoulesSDK.podspec
This PR updates the podspec to a new version that will include:
- Remove the Next bar- 
- Fixes for crashes caused by modifying the layout outside of the main thread
- Add feature to change the support email
- Add button to dismiss the Calendar Store
- Fix missing user id parameter when subscribing to a calendar
- Add Delegate method to inform the hosting app when the Calendar Store closes
- Add Notification to inform the hosting app when a `webcam` link is open
=> Update SchedJoulesSDK to 0.9.5

SDK/ViewControllers/CalendarItemViewController.swift
When opening a calendar, show the first upcoming event on top instead of the oldest available event in the calendar, in this PR we filter out the events that happen before today.
=> #50 Open calendar with first upcoming event

SDK/Store/StoreViewController.swift
This PR fixes a problem with dark mode on iOS where the text for the purchase screen was turned to white, and barely visible
=> #109 Fix for Dark mode problem

SDK/Store/StoreManager.swift, SDK/ViewControllers/Settings/SettingsViewController.swift
This PR fixes the crash found when restoring purchases from settings and a popup is presented from a background thread.
=> #113 Fix for crash when restoring purchases

Demo/AppDelegate.swift, SDK/Store/StoreViewController.swift, SDK/Utils/Extensions/UIColorExtension.swift, SDK/ViewControllers/CalendarItemViewController.swift, SDK/ViewControllers/PageViewController.swift, SDK/ViewControllers/Settings/SettingsDetailViewController.swift, SDK/ViewControllers/Settings/SettingsWebViewController.swift
As mentioned in https://github.com/schedjoules/ios-public-calendars-sdk/issues/111 the sdk has problems with modal presentations on iPad's
This PR fixes:
1. The size of the UITableView in `PageViewController`
2. The activity indicator in:
- PageViewController
- CalendarItemViewController
- SettingsDetailViewController
- SettingsWebViewController
3. The image in `StoreViewController`
=> #111 iPad Support

SDK/CalendarStoreViewController.swift
The navigation bar is transparent on iOS 13 and thise leaves the view behind it visible. The background color is now set to system background color which is dark mode compatible.
=> Fix for transparent navigation bar in iOS 13.

SDK/CalendarStoreViewController.swift
We shouldn't show the intro screens to the clients, so in this PR I removed the code that launches it.
This is a quick fix, still need to figure out a way to present it just for us.
Maybe take them out completely from the SDK and move it to our base project or use the bundle id to avoid launching
=> #125 Remove intro screens for clients

SchedJoulesSDK.podspec
Merge after PR: Remove intro screens https://github.com/schedjoules/ios-public-calendars-sdk/pull/126
##This version will include the follow changes:
1. Disable intro screens
2. Add an accessibility identifier for the done button, on the intro screens, suggested by Gahm
3. Workaround for empty NavBar, suggested by Gahm
=> Update SchedJoulesSDK to 0.9.8

SDK/Store/StoreViewController.swift
According to Apple reject reason, the "free trial" part must be less prominent than the price. The mention of "free trial" is now removed from the top title and text. A new label near the price has the trial mention in a non-bold font, same size as the price label which is now in a bold font.
This resolves #122
=> Make price more prominent than "free trial"
